import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import pokemonApi from '../services/pokemonApi'
import {Container} from './home'


export const getServerSideProps = async () => {

  let pokemons = await pokemonApi.getListPokemons()

  return {
    props: {
        pokemons
    }
  }
}

export default function Home({pokemons}) {

  return( 
    <Container >
      <Head>
        <title>Consume API Video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <div className="img">  <Image src="/pokedex_logo.png" width={180} height={70} /></div>
      <hr />

      <main>
        {
          pokemons && pokemons.results.map((pokemon) => (
            <div key={pokemon.name}>
              <h3>{pokemon.name}</h3>
            </div>
          ))
        } 
      </main>

    
    </Container>
  )
}
